---
title: "test"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }




###############################

# Newyork times data

NYTIMES_KEY="bivqAnNUnxs6CmliCOFeAbuMBIYVPHdn"


# Let's set some parameters
term <- "central+park+jogger" # Need to use + to string together separate words

baseurl <- paste0("http://api.nytimes.com/svc/search/v2/articlesearch.json?q=",term,
                  "&facet_filter=true&api-key=",NYTIMES_KEY, sep="")


initialQuery <- fromJSON(baseurl)
maxPages <- round((initialQuery$response$meta$hits[1] / 10)-1) 


pages <- list()
#6 pages
for(i in 0:5){
    nytSearch <- fromJSON(paste0(baseurl, "&page=", i), flatten = TRUE) %>% data.frame() 
    message("Retrieving page ", i)
    pages[[i+1]] <- nytSearch 
    Sys.sleep(1) 
}


allNYTSearch <- rbind_pages(pages)

allNYTSearch[[6]][1]

###############################

# fitbit data


library(httr)

library(curl)

# Read Fitbit token from file
token <- "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyMkJKWDYiLCJzdWIiOiI2NFRKUEsiLCJpc3MiOiJGaXRiaXQiLCJ0eXAiOiJhY2Nlc3NfdG9rZW4iLCJzY29wZXMiOiJ3aHIgd3BybyB3bnV0IHdzbGUgd3dlaSB3c29jIHdzZXQgd2FjdCB3bG9jIiwiZXhwIjoxNjExMDg5Mzg5LCJpYXQiOjE1Nzk1NTMzODl9.FzVyK6QPRCG5uCeoCVFz8911OGDZq-5QYc6qOZe71mA"

h <- new_handle()

handle_setheaders(
    h,
    'Authorization' = paste('Bearer', token)
)


date <- '2019-12-25'

# open the curl connection
hr.connection <- curl(
    paste0('https://api.fitbit.com/1/user/-/activities/heart/date/', date, '/1d/1min.json'), 
    handle = h
)

library(jsonlite)

# read to string object
# turn off warnings for no end-of-line character on final line
hr.string <- readLines( hr.connection, warn = FALSE )

hr.content <- fromJSON( hr.string )
str(hr.content)

hr.content$`activities-heart-intraday`$dataset


###############################

# fitbit data outh way



key <- "22BJZD"
secret <- "e015dc3261c64d95d505c9f2f86845f7"
fbr <- oauth_app('FitteR',key,secret)

accessTokenURL <-  'https://api.fitbit.com/oauth2/token'
authorizeURL <- 'https://www.fitbit.com/oauth2/authorize'
fitbit <- oauth_endpoint(authorize = authorizeURL, access = accessTokenURL)

token <- oauth2.0_token(fitbit,fbr, scope=c("activity", "heartrate", "sleep"), use_basic_auth = TRUE, oob_value = "https://www.shinyapps.io/",use_oob = TRUE)
conf <- config(token = token)



# https://cran.r-project.org/web/packages/httr/vignettes/quickstart.html

resp <- GET("https://api.fitbit.com/1/user/-/sleep/date/2019-06-30.json", config=conf)
cont <- content(resp, "parsed")
str(cont)




###############################




```
