---
title: "Cirque"
author: "Any"
date: "1/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r results='hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(tidytext)
library(scales)
library(textstem)

#select corpus and response variables
cirque <- read_csv("Data/Cirque_Train.csv")
corpus <- cirque$Text
response <- cirque$Show
#ratings <- 

#corpus <- med text
#response <- med response
#ratings <- med ratings

#create train model
model <- tibble::tibble(corpus, response)
```

```{r, warning=FALSE}
#Unigram and remove numbers and punctuations
clean_model <- model %>%
  mutate(id = row_number())
  group_by(response) %>%
  unnest_tokens(word, corpus, token = "ngrams", n = 1) %>%
  ungroup()
  
clean_model$word <- gsub('[[:punct:]]+', 'NA', clean_model$word)
clean_model$word <- gsub('[[:digit:]]+', 'NA', clean_model$word)

#root form
clean_model <- clean_model %>%
  mutate(word = lemmatize_words(word))

#Put titles words into a dataframe
titleWords <- tibble(omit = unique(clean_model$response))
titleWords <- titleWords %>%
  unnest_tokens(word, omit) %>%
  distinct()

#train <- train %>%
#  separate(word, c("word1", "word2"), sep = " ", remove = F) %>%
#  filter(!word1 %in% stop_words$word, !word2 %in% stop_words$word, !word1 %in% customWords$word, !word2 %in% #customWords$word, !word1 %in% "NA", !word2 %in% "NA") %>%
#  ungroup()

#Remove stop words and title words
clean_model <- clean_model %>%
  filter(!word %in% stop_words$word, !word %in% titleWords$word, !word %in% "NA") %>%
  ungroup()

#Show top 10 words that were most used in all documents
#Provide to user to select which words the user doesn't want to show
wordCount <- clean_model %>%
  count(word,sort = TRUE) %>%
  slice(1:20)

clean_model <- clean_model %>%
  filter(!word %in% wordCount$word) %>%
  mutate(ind = row_number())
```

```{r}
#tfidf1
#decided not to remove tf-idf
tmp <- words %>%
  count(response,word) %>%
  bind_tf_idf(word,response,n) %>%
  group_by(response) %>%
  arrange(desc(tf_idf)) %>%
  slice(1:15) %>%
  ungroup() %>%
  mutate(xOrder=n():1)

tmp
```
